// Generated by gencpp from file arduino_communicator/EncoderCounts.msg
// DO NOT EDIT!


#ifndef ARDUINO_COMMUNICATOR_MESSAGE_ENCODERCOUNTS_H
#define ARDUINO_COMMUNICATOR_MESSAGE_ENCODERCOUNTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace arduino_communicator
{
template <class ContainerAllocator>
struct EncoderCounts_
{
  typedef EncoderCounts_<ContainerAllocator> Type;

  EncoderCounts_()
    : header()
    , left_wheel_counts()
    , right_wheel_counts()
    , base_rotation_counts(0)
    , wrist_rotation_counts(0)
    , gripper_counts(0)  {
      left_wheel_counts.assign(0);

      right_wheel_counts.assign(0);
  }
  EncoderCounts_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_wheel_counts()
    , right_wheel_counts()
    , base_rotation_counts(0)
    , wrist_rotation_counts(0)
    , gripper_counts(0)  {
  (void)_alloc;
      left_wheel_counts.assign(0);

      right_wheel_counts.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<int32_t, 3>  _left_wheel_counts_type;
  _left_wheel_counts_type left_wheel_counts;

   typedef boost::array<int32_t, 3>  _right_wheel_counts_type;
  _right_wheel_counts_type right_wheel_counts;

   typedef int32_t _base_rotation_counts_type;
  _base_rotation_counts_type base_rotation_counts;

   typedef int32_t _wrist_rotation_counts_type;
  _wrist_rotation_counts_type wrist_rotation_counts;

   typedef int32_t _gripper_counts_type;
  _gripper_counts_type gripper_counts;




  typedef boost::shared_ptr< ::arduino_communicator::EncoderCounts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arduino_communicator::EncoderCounts_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderCounts_

typedef ::arduino_communicator::EncoderCounts_<std::allocator<void> > EncoderCounts;

typedef boost::shared_ptr< ::arduino_communicator::EncoderCounts > EncoderCountsPtr;
typedef boost::shared_ptr< ::arduino_communicator::EncoderCounts const> EncoderCountsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arduino_communicator::EncoderCounts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arduino_communicator::EncoderCounts_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arduino_communicator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'arduino_communicator': ['/home/carl/pegasus2/src/arduino_communicator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arduino_communicator::EncoderCounts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduino_communicator::EncoderCounts_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_communicator::EncoderCounts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_communicator::EncoderCounts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_communicator::EncoderCounts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_communicator::EncoderCounts_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arduino_communicator::EncoderCounts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "890e34750b24fc194afb98e978102a4f";
  }

  static const char* value(const ::arduino_communicator::EncoderCounts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x890e34750b24fc19ULL;
  static const uint64_t static_value2 = 0x4afb98e978102a4fULL;
};

template<class ContainerAllocator>
struct DataType< ::arduino_communicator::EncoderCounts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arduino_communicator/EncoderCounts";
  }

  static const char* value(const ::arduino_communicator::EncoderCounts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arduino_communicator::EncoderCounts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32[3] left_wheel_counts   # Front to back\n\
int32[3] right_wheel_counts  # Front to back\n\
int32 base_rotation_counts\n\
int32 wrist_rotation_counts\n\
int32 gripper_counts\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::arduino_communicator::EncoderCounts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arduino_communicator::EncoderCounts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_wheel_counts);
      stream.next(m.right_wheel_counts);
      stream.next(m.base_rotation_counts);
      stream.next(m.wrist_rotation_counts);
      stream.next(m.gripper_counts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncoderCounts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arduino_communicator::EncoderCounts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arduino_communicator::EncoderCounts_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_wheel_counts[]" << std::endl;
    for (size_t i = 0; i < v.left_wheel_counts.size(); ++i)
    {
      s << indent << "  left_wheel_counts[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.left_wheel_counts[i]);
    }
    s << indent << "right_wheel_counts[]" << std::endl;
    for (size_t i = 0; i < v.right_wheel_counts.size(); ++i)
    {
      s << indent << "  right_wheel_counts[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.right_wheel_counts[i]);
    }
    s << indent << "base_rotation_counts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.base_rotation_counts);
    s << indent << "wrist_rotation_counts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wrist_rotation_counts);
    s << indent << "gripper_counts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gripper_counts);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUINO_COMMUNICATOR_MESSAGE_ENCODERCOUNTS_H
